export const synonymMap: Record<string, string[]> = {
    hlađenje: ['hladnjaci', 'case cooler', 'cpu cooler', 'ventilatori'],
    kosilice: ['kosačice'],
    'tastature i miševi': ['podloga', 'miševi', 'tastature', 'kombo setovi'],
    'grejna tela': ['grejalice'],
    'HDCVI sistemi': ['kamere hd-tvi', 'kamere ip'],
    'matične ploče': ['matične ploče'],
    hdd: ['hard diskovi', 'eksterni hdd', 'eksterni hard disk'],
    ssd: ['M.2', 'eksterni ssd'],
    'mrežna oprema': ['ruteri'],
    šporeti: ['električni šporeti'],
    'ostala baštenska oprema': ['bazeni'],
    'veš mašine': ['mašine za pranje veša', 'pranje i sušenje veša', 'mašine za sušenje veša'],
    'pametni satovi i fitnes narukvice': ['smartwatch'],
    'stajleri i prese za kosu': ['nega kose', 'stajleri i prese'],
    'ostali kućni aparati': ['mali kućni aparati ostalo'],
    baterije: ['nepunjive baterije', 'punjači za baterije', 'punjive baterije', 'baterije za UPS-ove'],
    'memorijske kartice': ['memorijske kartice'],
    'laptop računari i oprema': ['laptopovi', 'oprema za laptopove', 'torbe, rančevi i futrole'],
    'tableti i oprema': ['tablet računari', 'oprema za tablete', 'grafičke table'],
    softver: ['operativni sistemi', 'software'],
    'mobilni telefoni': ['smart mobilni telefoni'],
    'oprema za mobilne telefone': ['punjači za mobilne telefone'],
    'usb memorije': ['usb flash'],
    'audio oprema': ['soundbar', 'audio, hi-fi'],
    'ups i oprema': ['ups i ispravljači'],
    'ugradna tehnika': ['ugradn'],
    štampači: ['štampac', 'laserski', 'inkjet'],
    skeneri: ['skeneri'],
    'televizori i oprema': ['televizori', 'oprema za tv'],
    'računari brandname': ['brand-name računari'],
    mikrotalasne: ['mikrotalasne rerne'],
    'aparati za tretiranje vazduha': ['ventilatori / osveživači / ovlaživači'],
    rasveta: ['led rasveta'],
    kuvala: ['ketleri - grejači vode'],
    'grilovi i tosteri': ['kontaktni gril / aparati za sendviče / roštilj'],
    posuđe: ['posuđe i kuhinjska oprema'],
    'serveri i oprema': ['serveri'],
    'monitori i dodatna oprema': ['monitori', 'dodatna oprema za monitore'],
    'kontroleri/kartice': ['mrežne kartice'],
    računari: ['all-in-one računari', 'desktop računari sa OS', 'desktop računari bez OS', 'mini pc'],
    'switch/hub': ['svičevi'],
    'gamepad/joystick/volani': ['gamepad', 'volan', 'joystick'],
    'interfonski sistemi': ['interfoni'],
    'ostali kuhinjski aparati': ['aparati za kuvanje na paru'],
    nameštaj: ['nameštaj', 'stolica'],
    slušalice: ['handsfree slušalice za mobilne telefone', 'gaming slušalice', 'bežične slušalice', 'slušalice bubice'],
    mikrofoni: ['mikrofoni'],
    'trotineti i bicikle': ['bicikle i fitnes', 'trotineti', 'oprema za bicikle'],
    'display, signage i oprema': ['interaktivni display'],
    'toneri, kertridži, mastila': ['toneri, kertridž, riboni, mastila', 'potrošni materijal'],
    'razni akumulatorski alati': ['razni električni i akumulatorski alati'],
}
